wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: huggingface
    huggingface_version: 4.26.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.8
    start_time: 1674799133.638748
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      3:
      - 16
      - 23
      4: 3.10.8
      5: 0.13.9
      6: 4.26.0
      8:
      - 1
      - 4
      - 5
architecture:
  desc: null
  value: Transformer
dataset:
  desc: null
  value: wikitext-2
epochs:
  desc: null
  value: 4
learning_rate:
  desc: null
  value: 5.0e-05
